---
title: ''
author: "Samuel Goëta"
date: '2022-07-11'
output: html_document
---

```{r}
library(tidyverse)
```
Import données ofgl
```{r}

ofgl <- read_csv2("https://data.ofgl.fr/explore/dataset/ofgl-base-communes-consolidee/download/?format=csv&disjunctive.reg_name=true&disjunctive.dep_name=true&disjunctive.epci_name=true&disjunctive.tranche_population=true&disjunctive.tranche_revenu_imposable_par_habitant=true&disjunctive.com_name=true&disjunctive.agregat=true&refine.exer=2020&refine.agregat=Achats+et+charges+externes&timezone=Europe/Berlin&lang=fr&use_labels_for_header=true&csv_separator=%3B")

ofgl_light <- ofgl %>% 
  select("Nom 2021 Commune","Code Siren Collectivité", "Population totale") %>% 
  mutate(`Code Siren Collectivité` = as.character(`Code Siren Collectivité`))

glimpse(ofgl_light)
```

Import observatoire open data des territoires
```{r}

obs_od <- read_csv("Organisations-Annuaire des Organisations.csv")

names(obs_od)
```

Jointure
```{r}

obs_od2 <- ofgl_light %>% 
  left_join(obs_od,by = c("Code Siren Collectivité" = "siren"))

no_od <- obs_od2 %>% 
  filter(is.na(nom))

names(no_od)
```

Export csv des communes sans open data
```{r}
write.csv(no_od, "no_od.csv")

```

